world.height: 500 # m
world.width: 500  # m
InfectionRegion.height: 300
InfectionRegion.width: 300

stop.at: 50000    # ticks

# Parameters for spawning agents
platoon.count: 16
squad.count: 5
noise.center: 0
noise.scale: 2

meet_log_file: './out/meet_log.csv'
agent_log_file: './out/agent_log.csv'

# Parameters for movement types
spread: 'random_waypoint' # 'random_walk' | 'random_waypoint' | 'hierarchical'
step_size: 1
